import { NavComponentsList } from "@/components/builder/components-list";
import { BuilderEditor } from "@/components/builder/editor";
import {
  Content,
  Header,
  Main,
  SideNav,
  ViewSwitcher,
} from "@/components/layout";
import { generateComponent } from "@/helpers/component";
import { useEditorReducer } from "@/helpers/reducer";
import {
  Box,
  Heading as ChakraHeading,
  Editable,
  EditableInput,
  EditablePreview,
  Flex,
  Stack,
} from "@chakra-ui/react";
import { Body, Container, Head, Html } from "@react-email/components";
import NextHead from "next/head";
import { useState } from "react";

export default function Home() {
  const [emailTitle, setEmailTitle] = useState("Email title");
  const [view, setView] = useState<"preview" | "source">("preview");

  const { state } = useEditorReducer();

  console.log(state);

  return (
    <>
      <NextHead>
        <title>React Email Builder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </NextHead>
      <Stack h="100vh" spacing="0" direction="row">
        <SideNav>
          <Flex px={6} h="70px" alignItems="center">
            <ChakraHeading size="sm" color="white">
              react email builder
            </ChakraHeading>
          </Flex>
          <Stack flex={1} as="nav" spacing={4} overflowY="auto">
            {state.componentToEdit ? <BuilderEditor /> : <NavComponentsList />}
          </Stack>
        </SideNav>
        <Main>
          <Header>
            <Editable
              value={emailTitle}
              onChange={(value) => setEmailTitle(value)}
            >
              <EditablePreview
                rounded="0"
                borderStyle="dashed"
                borderBottomWidth="1px"
              />
              <EditableInput />
            </Editable>
            <Box mx="auto">
              <ViewSwitcher activeView={view} onViewSwitch={setView} />
            </Box>
          </Header>
          <Content>
            <Box h="100%" mx="auto">
              <Html>
                <Head>
                  <title>{emailTitle}</title>
                </Head>
                <Body
                  style={{
                    backgroundColor: "#f6f9fc",
                    fontFamily: "HelveticaNeue,Helvetica,Arial,sans-serif",
                  }}
                >
                  <Container
                    style={{
                      margin: "0 auto",
                      marginBottom: "64px",
                      padding: "20px 0 48px",
                      backgroundColor: "#ffffff",
                    }}
                  >
                    {state.tree?.map((block) => {
                      return generateComponent(block);
                    })}
                  </Container>
                </Body>
              </Html>
            </Box>
          </Content>
        </Main>
      </Stack>
    </>
  );
}
